name: happy_app
description: "Happy!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_riverpod:
  go_router:
  flutter_svg:
  flutter_hooks:
  riverpod_annotation:
  riverpod_generator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  freezed:
  build_runner:

flutter:
    assets:
      - assets/images/
uses-material-design: true

